"""Updated pn_raw table for comments and resubmission

Revision ID: 2d3a5d79aef2
Revises: 891e4b5d4587
Create Date: 2024-08-13 16:59:02.943394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3a5d79aef2'
down_revision = '891e4b5d4587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_stl', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resubmission', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.drop_column('resubmission')
        batch_op.drop_column('comment_stl')

    # ### end Alembic commands ###
