"""Change primary key in WorkCat

Revision ID: 3cd540595569
Revises: 
Create Date: 2024-09-05 13:48:45.181057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cd540595569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_cat', schema=None) as batch_op:
        batch_op.alter_column('Rate_Code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_cat', schema=None) as batch_op:
        batch_op.alter_column('Rate_Code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
