"""Updated pn_raw table schema

Revision ID: 891e4b5d4587
Revises: 603d9c6634a8
Create Date: 2024-08-12 14:15:42.256005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '891e4b5d4587'
down_revision = '603d9c6634a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.alter_column('pn_date_issued_to_contractor',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('date_of_application',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('approved_quantity',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)
        batch_op.alter_column('approved_total',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)
        batch_op.alter_column('qgis_quant',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)
        batch_op.alter_column('qgis_rate',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.DECIMAL(precision=10, scale=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.alter_column('qgis_rate',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('qgis_quant',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('approved_total',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('approved_quantity',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=5),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('date_of_application',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('pn_date_issued_to_contractor',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
