"""Change primary key in WorkCat

Revision ID: 8b455b81479e
Revises: 3cd540595569
Create Date: 2024-09-05 14:13:49.004309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b455b81479e'
down_revision = '3cd540595569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_rate', schema=None) as batch_op:
        batch_op.alter_column('rate_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_rate', schema=None) as batch_op:
        batch_op.alter_column('rate_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
