"""Updated subcontractor_card table for set column

Revision ID: aa9ecb66ca42
Revises: 2d3a5d79aef2
Create Date: 2024-08-20 11:37:29.273800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa9ecb66ca42'
down_revision = '2d3a5d79aef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractor_rate', schema=None) as batch_op:
        batch_op.alter_column('set',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractor_rate', schema=None) as batch_op:
        batch_op.alter_column('set',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
