"""Updated pn table for seed foreign column

Revision ID: cc51788408b8
Revises: aa9ecb66ca42
Create Date: 2024-08-22 11:35:49.807645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc51788408b8'
down_revision = 'aa9ecb66ca42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eod_dump', ['seed'], ['Seed'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pn_raw', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
